# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master, develop, 'feature/**' ]
  pull_request:
    branches: [ master, develop, 'feature/**' ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install flake8
        pipenv install --python ${{matrix.python}}
    - name: Lint with flake8
      run: |
        pipenv run flake8 atomizer
    - name: Test with django test
      run: |
        pipenv run ./atomizer/manage.py test
